export const AIRPORT_COORDS: Record<string, { lat: number; lng: number; name: string; meetingPoint: string }> = {
  CTA: { lat: 37.4668, lng: 15.0664, name: 'Catania Fontanarossa',         meetingPoint: 'Terminal Arrivi — Uscita Bagagli, cerca il cartello Flanvo' },
  PMO: { lat: 38.1754, lng: 13.0914, name: 'Palermo Falcone Borsellino',   meetingPoint: 'Terminal Arrivi — Area Riconsegna Bagagli, cartello Flanvo' },
  CAG: { lat: 39.2515, lng: 9.0543,  name: 'Cagliari Elmas',               meetingPoint: 'Uscita Arrivi — Zona Attesa, cartello Flanvo' },
  FCO: { lat: 41.8003, lng: 12.2389, name: 'Roma Fiumicino',               meetingPoint: 'Terminal 1 — Uscita Arrivi B, cartello Flanvo' },
  MXP: { lat: 45.6301, lng: 8.7233,  name: 'Milano Malpensa',              meetingPoint: 'Terminal 1 — Arrivi, zona autisti, cartello Flanvo' },
  BGY: { lat: 45.6714, lng: 9.7042,  name: 'Milano Bergamo Orio',          meetingPoint: 'Uscita Arrivi — Zona NCC, cartello Flanvo' },
  NAP: { lat: 40.8860, lng: 14.2908, name: 'Napoli Capodichino',           meetingPoint: 'Arrivi — Zona Attesa Autisti, cartello Flanvo' },
  BRI: { lat: 41.1389, lng: 16.7606, name: 'Bari Karol Wojtyla',           meetingPoint: 'Uscita Arrivi — Parcheggio P1, cartello Flanvo' },
  LGW: { lat: 51.1537, lng: -0.1821, name: 'London Gatwick',               meetingPoint: 'South Terminal — Arrivals, Flanvo sign' },
  LHR: { lat: 51.4700, lng: -0.4543, name: 'London Heathrow',              meetingPoint: 'Terminal Arrivals — Meet & Greet, Flanvo sign' },
  BCN: { lat: 41.2974, lng: 2.0833,  name: 'Barcellona El Prat',           meetingPoint: 'Terminal 1 — Llegadas, cartel Flanvo' },
  CDG: { lat: 49.0097, lng: 2.5479,  name: 'Parigi Charles de Gaulle',     meetingPoint: 'Terminal 2E — Arrivées, panneau Flanvo' },
  AMS: { lat: 52.3086, lng: 4.7639,  name: 'Amsterdam Schiphol',           meetingPoint: 'Arrivals Hall — Schiphol Plaza, Flanvo sign' },
  FRA: { lat: 50.0379, lng: 8.5622,  name: 'Francoforte',                  meetingPoint: 'Terminal 1 — Ankunft B, Flanvo Schild' },
  MAD: { lat: 40.4719, lng: -3.5626, name: 'Madrid Barajas',               meetingPoint: 'Terminal 4 — Llegadas, cartel Flanvo' },
};
